export const TERMS = [
    {
        text: "PLEASE CAREFULLY READ THE FOLLOWING TERMS AND CONDITIONS (\"TERMS OF SERVICE,\" \"TERMS OF USE,\" OR \"TERMS\") BEFORE ENGAGING IN CLIENT-SERVICE RELATIONSHIPS WITH STAKECRAFT (\"STAKECRAFT,\" \"THE COMPANY,\" \"SERVICE,\" \"PLATFORM,\" \"US,\" \"OUR,\" OR \"WE\") THROUGH THE WEBSITE HTTPS://STAKECRAFT.COM/ (\"THE WEBSITE\"). STAKECRAFT OPERATES, HOSTS, AND PROVIDES STAKING SERVICES THROUGH VALIDATING NODES ACROSS VARIOUS BLOCKCHAIN NETWORKS.\n" +
                  "\n" +
                  "BY ACCESSING THE WEBSITE, UTILIZING ITS FUNCTIONALITY, OR ENGAGING WITH ANY OTHER STAKECRAFT SERVICE, WHETHER AS AN INDIVIDUAL OR A COMPANY, AND BY PROVIDING OR SUBMITTING ANY INFORMATION TO US, YOU CONSENT TO AND AGREE TO ABIDE BY THESE TERMS OF USE.\n" +
                  "\n" +
                  "AS A USER OF THE PLATFORM (\"CLIENT,\" \"USER,\" \"INDIVIDUAL,\" OR \"YOU\"), YOU ARE REQUIRED TO COMPLY WITH THESE TERMS OF USE AND ANY OTHER POLICIES, PROCEDURES, OR RULES IMPOSED BY THE SERVICE. PLEASE NOTE THAT THE TERMS AND CONDITIONS, AS WELL AS OTHER POLICIES, PROCEDURES, OR RULES, ARE SUBJECT TO CHANGE. THE COMPANY RESERVES THE RIGHT TO MODIFY THEM WITHOUT PRIOR NOTICE TO ITS CLIENTS. IF YOU DO NOT AGREE TO THESE TERMS AND CONDITIONS, YOU ARE NOT PERMITTED TO VIEW OR USE THE WEBSITE OR STAKECRAFT SERVICES."
    },
    {
        title: "REGULATORY COMPLIANCE",
        text:  "AS A CLIENT, IT IS YOUR RESPONSIBILITY TO ENSURE THAT YOUR USAGE OF THE SERVICE COMPLIES WITH ALL APPLICABLE LAWS AND REGULATIONS. YOU MUST WARRANT AND REPRESENT THAT YOU WILL COMPLY WITH ANY RELEVANT DATA PRIVACY LAWS AND REGULATIONS, SUCH AS GLB, HIPAA, GDPR, OR ANY OTHER APPLICABLE LAWS. IT IS YOUR SOLE RESPONSIBILITY TO DETERMINE WHETHER THE STAKECRAFT SERVICE IS SUITABLE FOR YOU IN LIGHT OF THESE LAWS AND REGULATIONS. IF YOU ARE SUBJECT TO ANY OF THE AFOREMENTIONED LAWS OR REGULATIONS AND CHOOSE TO USE OUR SERVICE, STAKECRAFT WILL NOT BE HELD LIABLE IF THE PLATFORM DOES NOT MEET THE REQUIRED CRITERIA.\n" +
                   "\n" +
                   "ADDITIONALLY, YOU ARE FULLY ACCOUNTABLE FOR COMPLYING WITH ANY OTHER LAWS AND REGULATIONS IN YOUR JURISDICTION THAT MAY EITHER RESTRICT OR PERMIT THE USE OF SERVICES LIKE STAKECRAFT. STAKECRAFT BEARS NO RESPONSIBILITY FOR ANY ACTIONS YOU TAKE THAT VIOLATE THE LAWS IN YOUR JURISDICTION WHILE USING THE SERVICE."
    },
    {
        title: "OWNERSHIP AND INTELLECTUAL PROPERTY",
        text:  "STAKECRAFT IS THE SOLE OWNER OF ALL PROPRIETARY RIGHTS ASSOCIATED WITH THE SERVICE, INCLUDING THE DOMAIN (HTTPS://STAKECRAFT.COM/), MARKETING MATERIALS SUCH AS LOGOS, COLOR SCHEMES, AND DESIGN. THIS OWNERSHIP EXTENDS TO VARIOUS FORMS OF INTELLECTUAL PROPERTY, INCLUDING BUT NOT LIMITED TO COPYRIGHTS, TRADEMARKS, TRADE SECRETS, SERVICE MARKS, DEVELOPMENT PRACTICES, PROPRIETARY SOFTWARE, AND OTHER INTELLECTUAL PROPERTY RIGHTS. AS A CLIENT, IT IS YOUR OBLIGATION TO UPHOLD AND RESPECT THE INTELLECTUAL PROPERTY RIGHTS OF STAKECRAFT AS OUTLINED ABOVE, AS THEY ARE PROTECTED BY LAW.",
    },
    {
        title: "USE LICENSE",
        text:  "YOU ARE AUTHORIZED TO USE OUR SERVICE AS PROVIDED BY STAKECRAFT, WITHOUT MAKING ANY MODIFICATIONS TO THE SOFTWARE OR SERVICE WE OFFER. IT IS STRICTLY PROHIBITED TO MODIFY ANY SOFTWARE CREATED BY OUR COMPANY WITHOUT PRIOR NOTICE, AS WELL AS TO EXTRACT AND UTILIZE SOURCE CODE CREATED BY STAKECRAFT.\n" +
                   "\n" +
                   "YOU ARE PROHIBITED FROM ENGAGING IN ANY UNLAWFUL ACTIVITIES THAT MAY SIGNIFICANTLY BURDEN OUR INFRASTRUCTURE OR DISRUPT THE NORMAL FUNCTIONING OF THE COMPANY. THIS INCLUDES ATTEMPTING TO BYPASS OR CIRCUMVENT SECURITY MECHANISMS, GAINING UNAUTHORIZED ACCESS TO OUR COMPUTER SYSTEMS, CONDUCTING ACTIVITIES THAT DISRUPT THE COMPANY'S OPERATIONS, OR DEPLOYING MALICIOUS CODE SUCH AS WORMS, TROJANS, CRYPTOJACKING SOFTWARE, OR ANY OTHER FORM OF COMPUTER VIRUSES AGAINST THE COMPANY, INCLUDING COMPUTER NETWORKS OR SYSTEMS.\n" +
                   "\n" +
                   "LAUNCHING ANY SOFTWARE OR DEVICES (\"CRAWLERS,\" \"SPIDERS,\" \"AUTO-RESPONDERS\") ON THE COMPANY WITH THE PURPOSE OF AUTOMATICALLY OR MANUALLY COLLECTING DATA FROM THE WEBSITE OR SPAMMING IS ALSO STRICTLY PROHIBITED. VIOLATING THESE RULES WILL RESULT IN THE AUTOMATIC TERMINATION OF THE \"USE LICENSE,\" AND THE INDIVIDUAL'S ACCOUNT WILL BE SUSPENDED ACCORDINGLY. IF A USER OR ANY OTHER INDIVIDUAL CAUSES DAMAGE TO ANY PART OF THE SERVICE THROUGH A CYBER ATTACK, THE INCIDENT WILL BE THOROUGHLY REVIEWED AND REPORTED TO THE APPROPRIATE LAW ENFORCEMENT AGENCY, WHICH WILL TAKE APPROPRIATE ACTION IN RESPONSE.\n" +
                   "\n" +
                   "PLEASE NOTE THAT THE TERMS AND CONDITIONS MENTIONED ABOVE ARE SUBJECT TO CHANGE, AND STAKECRAFT RESERVES THE RIGHT TO MODIFY THEM WITHOUT PRIOR NOTICE.",
    },
    {
        title: "STAKECRAFT SERVICE PROVISION AND TERMINATION",
        text:  "STAKECRAFT OFFERS STAKING SERVICES TO CLIENTS THROUGH VALIDATING NODES. THE COMPANY INDEPENDENTLY DETERMINES THE REQUIRED HARDWARE AND NETWORK SPECIFICATIONS TO ENSURE A STABLE AND EFFICIENT STAKING SERVICE FOR CLIENTS.\n" +
                   "\n" +
                   "STAKECRAFT IS RESPONSIBLE FOR SERVER MAINTENANCE, INSTALLATION OF NEW HARDWARE, SERVER UPGRADES, AND SOFTWARE UPDATES. ALL COSTS ASSOCIATED WITH THESE OPERATIONS ARE COVERED BY THE COMPANY.\n" +
                   "\n" +
                   "THE REVENUE SHARE PAYMENTS PROVIDED BY STAKECRAFT ARE BASED ON THE AMOUNT OF CRYPTOCURRENCY STAKED BY THE CLIENT. THE SPECIFIC PAYOUT PERCENTAGES VARY DEPENDING ON THE TYPE OF STAKED CRYPTOCURRENCY, AND THIS INFORMATION CAN BE FOUND ON THE HOMEPAGE OF THE WEBSITE IN THE \"COINS\" SECTION."
    },
    {
        title: "REPRESENTATIONS AND WARRANTIES",
        text:  "EACH PARTY HEREBY REPRESENTS AND WARRANTS TO THE OTHER PARTY THE FOLLOWING:\n" +
                   "\n" +
                   "(I) IT IS DULY ORGANIZED, VALIDLY EXISTING, AND IN GOOD STANDING UNDER THE LAWS OF ITS JURISDICTION OF ORGANIZATION. FURTHERMORE, IT POSSESSES THE LEGAL AUTHORITY TO ENTER INTO THESE TERMS OF USE.\n" +
                   "\n" +
                   "(II) THE EXECUTION, DELIVERY, AND PERFORMANCE OF THESE TERMS OF USE, AS WELL AS THE COMPLETION OF THE TRANSACTIONS CONTEMPLATED HEREIN, ARE WITHIN THE CORPORATE POWERS OF THE PARTY. ALL NECESSARY CORPORATE ACTIONS HAVE BEEN DULY AUTHORIZED BY THE PARTY, AND THIS AGREEMENT CONSTITUTES A VALID AND BINDING AGREEMENT FOR THE PARTY.\n" +
                   "\n" +
                   "(III) THE PARTY HAS FULL POWER, AUTHORITY, AND RIGHT TO FULFILL ITS OBLIGATIONS AND GRANT THE RIGHTS STATED IN THESE TERMS OF USE.\n" +
                   "\n" +
                   "(IV) THE PARTY'S PERFORMANCE UNDER THESE TERMS OF USE WILL COMPLY WITH ALL APPLICABLE LAWS, RULES, AND REGULATIONS, INCLUDING BUT NOT LIMITED TO NATIONAL AND INTERNATIONAL LAWS, REGULATIONS, NOTICES, AND GUIDELINES PERTAINING TO INFORMATION PRIVACY.\n" +
                   "\n" +
                   "THESE REPRESENTATIONS AND WARRANTIES ARE MADE BY EACH PARTY INDIVIDUALLY AND SHALL REMAIN IN EFFECT THROUGHOUT THE DURATION OF THESE TERMS OF USE."
    },
    {
        title:           "PROHIBITION OF USE",
        text:            "IT IS IMPORTANT TO ACKNOWLEDGE THAT STAKECRAFT'S ABILITY TO PROVIDE CERTAIN PRODUCTS AND SERVICES MAY BE SUBJECT TO LEGAL REQUIREMENTS IN DIFFERENT JURISDICTIONS. AS A RESULT, CERTAIN PRODUCTS, SERVICES, OR SPECIFIC FUNCTIONALITIES WITHIN THE STAKECRAFT SERVICES MAY NOT BE AVAILABLE OR MAY BE RESTRICTED IN PARTICULAR JURISDICTIONS, REGIONS, OR FOR CERTAIN USERS.\n" +
                             "\n" +
                             "IT IS YOUR RESPONSIBILITY TO FAMILIARIZE YOURSELF WITH AND ADHERE TO ANY RESTRICTIONS OR REQUIREMENTS REGARDING THE ACCESS AND USE OF THE STAKECRAFT SERVICES IN EACH JURISDICTION FROM WHICH YOU OR SOMEONE ACTING ON YOUR BEHALF ACCESSES THE SERVICES. STAKECRAFT RESERVES THE RIGHT, AT OUR DISCRETION AND WITHOUT PRIOR NOTICE, TO MODIFY, CHANGE, OR IMPOSE ADDITIONAL RESTRICTIONS ON THE ACCESS AND USE OF THE STAKECRAFT SERVICES.\n" +
                             "\n" +
                             "PLEASE ENSURE THAT YOU STAY INFORMED AND COMPLY WITH ANY APPLICABLE RESTRICTIONS OR REQUIREMENTS WHEN ACCESSING AND UTILIZING THE STAKECRAFT SERVICES IN VARIOUS JURISDICTIONS.",
        highlightedText: "BY ACCESSING AND USING STAKECRAFT SERVICES, YOU REPRESENT AND WARRANT THAT YOU HAVE NOT BEEN INCLUDED IN ANY TRADE EMBARGOES OR ECONOMIC SANCTIONS LIST (SUCH AS THE UNITED NATIONS SECURITY COUNCIL SANCTIONS LIST), THE LIST OF SPECIALLY DESIGNATED NATIONALS MAINTAINED BY OFAC (THE OFFICE OF FOREIGN ASSETS CONTROL OF THE U.S. DEPARTMENT OF THE TREASURY), HAVE NOT BEEN DESIGNATED BY THE U.S. GOVERNMENT AS A “TERRORIST SUPPORTING” JURISDICTION, HAVE NOT BEEN INCLUDED IN THE DENIED PERSONS OR ENTITY LIST OF THE U.S. DEPARTMENT OF COMMERCE OR THAT YOU ARE NOT LISTED ON ANY U.S. GOVERNMENT LIST OF PROHIBITED OR RESTRICTED PARTIES.\n" +
                             "\n" +
                             "STAKECRAFT RESERVES THE RIGHT TO CHOOSE MARKETS AND JURISDICTIONS TO CONDUCT BUSINESS, AND MAY RESTRICT OR REFUSE, IN ITS DISCRETION, THE PROVISION OF STAKECRAFT SERVICES IN CERTAIN JURISDICTIONS."
    },
    {
        title:           "LIMITATION OF LIABILITY",
        highlightedText: "NO PARTY TO THE TERMS WILL BE LIABLE FOR ANY INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES, INCLUDING LOST PROFITS, LOSS OF DATA OR GOODWILL, SERVICE INTERRUPTION, COMPUTER DAMAGE OR SYSTEM FAILURE, OR THE COST OF SUBSTITUTE SERVICES ARISING OUT OF OR IN CONNECTION WITH THE TERMS OR FROM THE USE OF OR INABILITY TO USE THE SERVICES, WHETHER BASED ON WARRANTY, CONTRACT, TORT (INCLUDING NEGLIGENCE), OR ANY OTHER LEGAL THEORY, AND WHETHER OR NOT SUCH PARTY HAS BEEN INFORMED OF THE POSSIBILITY OF SUCH DAMAGE. SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OR LIMITATION OF LIABILITY FOR CONSEQUENTIAL OR INCIDENTAL DAMAGES, SO THE ABOVE LIMITATION MAY NOT APPLY.\n" +
                             "\n" +
                             "TO THE FULLEST EXTENT PERMITTED BY LAW, IN NO EVENT WILL CLIENT’S OR COMPANY’S TOTAL LIABILITY TO THE OTHER ARISING OUT OF OR IN CONNECTION WITH THE TERMS OR FROM THE USE OF OR INABILITY TO USE THE SERVICES EXCEED THE AMOUNTS PAID OR PAYABLE BY CLIENT TO COMPANY FOR USE OF THE SERVICES DURING THE TWELVE (12) MONTH PERIOD PRIOR TO THE DATE WHEN THE CLAIM OR LIABILITY FIRST AROSE"
    },
    {
        title: "COMPLIANCE WITH LAWS/COPYRIGHT",
        text:  "EACH PARTY INVOLVED SHALL ADHERE TO ALL APPLICABLE LAWS WHILE CARRYING OUT THEIR OBLIGATIONS AND EXERCISING THEIR RIGHTS WITHIN THE SERVICES. THIS INCLUDES COMPLIANCE WITH COPYRIGHT LAWS IN ALL JURISDICTIONS WHERE THE COMPANY OPERATES, AND IT EXPECTS THE SAME FROM ITS CLIENTS. THE COMPANY RESERVES THE RIGHT TO TERMINATE, UNDER APPROPRIATE CIRCUMSTANCES, CLIENTS WHO ARE FOUND TO INFRINGE UPON OR ARE BELIEVED TO BE INFRINGING UPON THE RIGHTS OF COPYRIGHT HOLDERS.",
    },
    {
        title: "CONFIDENTIAL INFORMATION AND CONFIDENTIALITY OBLIGATIONS",
        text:  "THE COMPANY ACKNOWLEDGES THAT IT MAY COME INTO POSSESSION OF CONFIDENTIAL INFORMATION BELONGING TO THE CLIENT, AND THE CLIENT ACKNOWLEDGES THAT IT MAY RECEIVE CONFIDENTIAL INFORMATION FROM THE COMPANY. BOTH PARTIES AGREE NOT TO DISCLOSE ANY CONFIDENTIAL INFORMATION OF THE OTHER PARTY TO ANY THIRD PARTY AND NOT TO UTILIZE ANY CONFIDENTIAL INFORMATION FOR PURPOSES BEYOND WHAT IS OUTLINED IN THE TERMS.",
    }

];

export default TERMS;
