name: deploy-to-dev-server
run-name: ${{ github.actor }} is deploying code to dev environment
on:
  push:
    branches:
    - dev
    - ayoub_dev
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: pull diff and restart services
        env:
          SERVER_ENV:  ${{ secrets.SERVER_ENV }}
          AUTH_CONFIG: ${{ secrets.AUTH_CONFIG }}
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd ~/stakecraft.com-development
            git pull
            cd stakecraftFE/
            npm install --legacy-peer-deps
            npm run build
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USER }}
          port: ${{ secrets.PORT }}
          key:  ${{ secrets.PRIVATE_KEY }}
          args: "-o StrictHostKeyChecking=no"